name: scout
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.10.0
  flutter_mobx: ^1.0.1
  http: ^0.12.2
  geolocator: ^6.0.0+4
  flutter_spinkit: ^4.1.2+1
  animated_text_kit: ^2.5.0
  modal_progress_hud: ^0.1.3
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/

  fonts:
    - family: Pacifico
      fonts:
      - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Roboto
      fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
    - family: SourceSansPro
      fonts:
      - asset: assets/fonts/SourceSansPro-Regular.ttf